### ISSUE TITLE
Fix inconsistent JWT issuer

### ISSUE THREAD

**Issue by stefanbitcr** [BitcreditProtocol/Wildcat#193]
The JWT token iss needs to match the issuer in envoy. 

In the setup for the dashboard, the URLs need to match exactly

```
                        keycloak_provider_external_secure:
                          issuer: https://keycloak.wildcat-dev-docker.minibill.tech/realms/dev
                          remote_jwks:
                            http_uri:
                              uri: http://keycloak:8080/realms/dev/protocol/openid-connect/certs
                              cluster: keycloak_service
                              timeout: 5s
                            cache_duration:
                              seconds: 600
                          forward_payload_header: x-jwt-payload
                      rules:
                        - match: { prefix: "/v1/admin" }
                          requires:
                            requires_any:
                              requirements:
                                - provider_name: keycloak_provider_external_secure
                                - provider_name: keycloak_provider_service
```

Add secure in addition to the localhost that keycloak that we have for testing.

**Comment by stefanbitcr** [comment]
Full envoy config:


```
static_resources:
  listeners:
    - name: listener_http
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 4242
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: admin_api
                      domains: ["*"]
                      typed_per_filter_config:
                        envoy.filters.http.cors:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
                          allow_origin_string_match:
                          #- exact: "https://wildcat-dashboard.pages.dev"
                          - suffix: ".pages.dev"
                          - suffix: ".minibill.tech"
                          - prefix: "http://localhost:"
                          - prefix: "http://127.0.0.1:" 
                          allow_methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
                          allow_headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Access-Control-Allow-Origin"
                          allow_credentials: true
                          max_age: "1728000"
                      routes:
                        - match: { prefix: "/v1/admin/credit" }
                          route: { cluster: quote_service }
                        - match: { prefix: "/v1/admin/balance" }
                          route:
                            cluster: treasury_service
                            prefix_rewrite: "/v1/balance"
                        - match: { prefix: "/v1/admin/keys" }
                          route: { cluster: key_service }
                        - match: { prefix: "/v1/admin/onchain" }
                          route:
                            cluster: ebpp_service
                            prefix_rewrite: "/v1/onchain"
                http_filters:
                  - name: envoy.filters.http.cors
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                  - name: envoy.filters.http.jwt_authn
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                      providers:
                        keycloak_provider_service:
                          issuer: http://keycloak:8080/realms/dev
                          remote_jwks:
                            http_uri:
                              uri: http://keycloak:8080/realms/dev/protocol/openid-connect/certs
                              cluster: keycloak_service
                              timeout: 5s
                            cache_duration:
                              seconds: 600
                          forward_payload_header: x-jwt-payload
                        keycloak_provider_external_secure:
                          issuer: https://keycloak.wildcat-dev-docker.minibill.tech/realms/dev
                          remote_jwks:
                            http_uri:
                              uri: http://keycloak:8080/realms/dev/protocol/openid-connect/certs
                              cluster: keycloak_service
                              timeout: 5s
                            cache_duration:
                              seconds: 600
                          forward_payload_header: x-jwt-payload
                      rules:
                        - match: { prefix: "/v1/admin" }
                          requires:
                            requires_any:
                              requirements:
                                - provider_name: keycloak_provider_external_secure
                                - provider_name: keycloak_provider_service
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: quote_service
      connect_timeout: 5s
      type: STRICT_DNS
      load_assignment:
        cluster_name: quote_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: quote-service
                      port_value: 3338

    - name: treasury_service
      connect_timeout: 5s
      type: STRICT_DNS
      load_assignment:
        cluster_name: treasury_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: treasury-service
                      port_value: 3338

    - name: key_service
      connect_timeout: 5s
      type: STRICT_DNS
      load_assignment:
        cluster_name: key_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: key-service
                      port_value: 3338

    - name: ebpp_service
      connect_timeout: 5s
      type: STRICT_DNS
      load_assignment:
        cluster_name: ebpp_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: ebpp
                      port_value: 9090

    - name: keycloak_service
      connect_timeout: 5s
      type: STRICT_DNS
      load_assignment:
        cluster_name: keycloak_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: keycloak
                      port_value: 8080

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

```

**Comment by stefanbitcr** [comment]
@cleot Can you make a PR to update the config

and change the EBPP port to 3338 as well

```
    - name: ebpp_service
      connect_timeout: 5s
      type: STRICT_DNS
      load_assignment:
        cluster_name: ebpp_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: ebpp
                      port_value: 3338
```
